version: '3.5'

services:

  backend:
    build: .
    container_name: kanban_backend
    restart: unless-stopped
    command: gunicorn kanban.wsgi --bind 0.0.0.0:8007
    volumes:
      - static_value:/kanban/static/
      - media_value:/kanban/media/
      - ./db.sqlite3:/kanban/db.sqlite3
    env_file:
      - ./.env

  nginx:
    image: nginx:latest
    container_name: kanban_nginx
    restart: unless-stopped
    ports:
      - '8007:8007'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend

volumes:
  static_value:
  media_value:
