name: Deploy kanban

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  copy_files:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: copy start files via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          source: "*,!.git,!.github,!.venv,!.env, !db.sqlite3"
          target: "~/kanban"
          overwrite: true

  deploy:
    runs-on: ubuntu-latest
    needs: copy_files
    steps:
      - name: executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            cd kanban
            sudo docker compose stop
            sudo docker compose rm kanban_backend
            touch .env
            echo SECRET_KEY=${{ secrets.SECRET_KEY }} > .env
            sudo docker compose up -d --build

  send_message:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
    - name: send telegram message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: ${{ github.workflow }} completed successfully!
